services:
  mysql:
    image: mysql:8.0
    container_name: golf_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: golf_db
      MYSQL_USER: app
      MYSQL_PASSWORD: 123456789De
    ports:
      - "3307:3306" # Đổi host port -> use 3307 nếu 3306 đang bận trên máy
    command: ["--default-authentication-plugin=mysql_native_password"]
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test:
        ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-u", "root", "-proot"]
      interval: 5s
      timeout: 3s
      retries: 20

  phpmyadmin:
    image: phpmyadmin:5
    container_name: golf_phpmyadmin
    restart: unless-stopped
    ports:
      - "8081:80" # Đổi host port để tránh xung 8080
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: root
      UPLOAD_LIMIT: 64M
    depends_on:
      mysql:
        condition: service_healthy

  backend:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    container_name: golf_backend
    restart: unless-stopped
    working_dir: /var/www
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/var/www
      - backend_vendor:/var/www/vendor
    ports:
      - "9000:9000"
    command: php artisan serve --host=0.0.0.0 --port=9000
    depends_on:
      - mysql

  frontend:
    build:
      context: . # build từ gốc repo
      dockerfile: docker/frontend/Dockerfile
    container_name: golf_frontend
    working_dir: /usr/src/app # khớp với WORKDIR của Dockerfile
    volumes:
      - ./frontend:/usr/src/app
      - frontend_node_modules:/usr/src/app/node_modules
    ports:
      - "5174:5173"
    command: ["npm", "run", "dev", "--", "--host"]
    depends_on:
      - backend

volumes:
  mysql_data:
  frontend_node_modules:
  backend_vendor:
