services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: golf_db
      MYSQL_USER: app
      MYSQL_PASSWORD: 123456789De
    ports:
      - "3306:3306"
    command: ["--default-authentication-plugin=mysql_native_password"]
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test:
        ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-u", "root", "-proot"]
      interval: 5s
      timeout: 3s
      retries: 20

  phpmyadmin:
    image: phpmyadmin:5
    container_name: phpmyadmin
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: root
      UPLOAD_LIMIT: 64M
    depends_on:
      mysql:
        condition: service_healthy

  backend:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    container_name: backend
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./backend:/var/www
      - backend_vendor:/var/www/vendor
    depends_on:
      - mysql
    env_file:
      - ./backend/.env
    ports:
      - "9000:9000"
    command: php artisan serve --host=0.0.0.0 --port=9000

  frontend:
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
    container_name: frontend
    working_dir: /usr/src/app
    volumes:
      - ./frontend:/usr/src/app
      - frontend_node_modules:/usr/src/app/node_modules
    ports:
      - "5173:5173"
    command: ["npm", "run", "dev", "--", "--host"]
    depends_on:
      - backend

volumes:
  mysql_data:
  frontend_node_modules:
  backend_node_modules:
  backend_vendor:
